---
language: nodejs
version: '4.0'
docs:
  -
    type: html
    folder: doc/
    main: index.html
    env:
      TEST_ENV: ciao
      COMMIT: false 
  -
    type: artefact
    folder: /
    main: doc.zip
    script: npm run doczip

